spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/DevelHopeDB
    username: TongyAdmin
    password: Tongy_Admin1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: develhope.test@gmail.com
    password: develhope2022
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    serialization:
      fail-on-empty-beans: false