spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: develhope.test@gmail.com
    password: develhope2022
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true